name: 'Business Greetings'
description: 'Offers professional greetings and timestamps them'
inputs:
  name:
    description: 'Name of the person or team to greet'
    required: true
    default: 'Udacity Learner'
outputs:
  timestamp:
    description: 'Time of greeting'
runs:
  using: 'node20'
  main: 'vicky9039/business-greetings-action/.github/workflows/index.js'