name: My First Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3    

    - name: run custom action
      uses: vicky9039/business-greetings-action/.github/workflows@main